django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views

movie_resource = MovieResource()

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls))
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail')
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie
# We use resource to differentiate the "APP data model" from the "REST resources"
# derive this class from the tastypie ModelResources class


class MovieResource(ModelResource):
    # tatsypie looks for an innerclass called Meta: which define some meta data about our movie rosources
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'

movies/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=255)
    # change the string representation of Genre

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

django_project/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'django_project/home.html')

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Movie
# Create your views here.


def index(request):
    ''' # SELECT * FROM movies_movie WHERE release_year = 1989
    Movie.objects.filter(release_year=1989)
    # Movie.objects.get(id=1) '''
    # SELECT * FROM movies_movie
    movies = Movie.objects.all()
    ''' output = ','.join([m.title for m in movies])
    return HttpResponse(output)  '''
    return render(request, 'movies/index.html', {'movies': movies})


# in urls.py we use movie_id as parameter, when user send request to movies/1, django will automatically extract 1, and then it will call this view function and pass 1 as argument
def detail(request, movie_id):
    # return HttpResponse(movie_id)
    ''' try:
        movie = Movie.objects.get(pk=movie_id)
        return render(request, 'movies/detail.html', {'movie': movie})
    # DoesNotExist is part of our Movie Model who inherent models.Model
    except Movie.DoesNotExist:
        raise Http404() '''
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <title>Movies</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="#">Movies</a>
    </nav>
    <main class="container">{% block content %} {% endblock %}</main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/django_project/home.html
{% extends 'base.html'%} {% block content %}
<a href="{% url 'movies:index' %}">Movies</a>
{% endblock %}

templates/movies/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% extends 'base.html' %} {% block content %}
    <dl>
      <dt>Title</dt>
      <dd>{{ movie.title }}</dd>
      <dt>Genre</dt>
      <dd>{{ movie.genre }}</dd>
      <dt>Stock</dt>
      <dd>{{ movie.number_in_stock }}</dd>
    </dl>
    {% endblock %}
  </body>
</html>

templates/movies/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% extends 'base.html'%} {% block content %}

    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Genre</th>
          <th>Stock</th>
          <th>Daily Rate</th>
        </tr>
      </thead>
      <tbody>
        {% for movie in movies %}
        <tr>
          <td>
            <a href="{% url 'movies:detail' movie.id %}"> {{ movie.title }} </a>
          </td>
          <td>{{ movie.genre }}</td>
          <td>{{ movie.number_in_stock }}</td>
          <td>{{ movie.daily_rate }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endblock %}
  </body>
</html>